name: Check pull requests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.0.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: flutter pub get
